name: Check App

on:
  push:
    branches:
      - master

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - uses: actions/setup-node@v4
        with:
          cache: "npm"
          node-version: "18"
      - name: Install dependencies
        run: npm ci # ci = clean install ==> Lo mismo que npm i/install, pero más rapido, checkeq el packjson-lock
        # run: npm i --no-audit --no-fund --no-optional #Para quitar los datos extras de las intall e.g. 37pckges install , etc
      - name: Ejecutar esLint
        run: npm run eslint
      - name: Test
        run: npm test
